// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 33: // ['!','!']
			return 2
		case r == 34: // ['"','"']
			return 3
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 5
		case r == 39: // [''',''']
			return 4
		case r == 40: // ['(','(']
			return 6
		case r == 41: // [')',')']
			return 7
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 44: // [',',',']
			return 8
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 4
		case r == 60: // ['<','<']
			return 9
		case r == 61: // ['=','=']
			return 10
		case r == 62: // ['>','>']
			return 11
		case r == 63: // ['?','?']
			return 4
		case r == 65: // ['A','A']
			return 12
		case 66 <= r && r <= 90: // ['B','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 4
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 100: // ['a','d']
			return 13
		case r == 101: // ['e','e']
			return 14
		case 102 <= r && r <= 104: // ['f','h']
			return 13
		case r == 105: // ['i','i']
			return 15
		case 106 <= r && r <= 109: // ['j','m']
			return 13
		case r == 110: // ['n','n']
			return 16
		case 111 <= r && r <= 122: // ['o','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 17
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 18
		case r == 33: // ['!','!']
			return 18
		case r == 34: // ['"','"']
			return 19
		case 35 <= r && r <= 91: // ['#','[']
			return 18
		case r == 92: // ['\','\']
			return 20
		case 93 <= r && r <= 1114111: // [']',\U0010ffff]
			return 18
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 4
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 4
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 4
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 4
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 21
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 4
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 4
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 4
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 4
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 17
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 22
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 17
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 77: // ['A','M']
			return 13
		case r == 78: // ['N','N']
			return 24
		case 79 <= r && r <= 90: // ['O','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 119: // ['a','w']
			return 13
		case r == 120: // ['x','x']
			return 26
		case 121 <= r && r <= 122: // ['y','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 109: // ['a','m']
			return 13
		case r == 110: // ['n','n']
			return 27
		case 111 <= r && r <= 122: // ['o','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 110: // ['a','n']
			return 13
		case r == 111: // ['o','o']
			return 28
		case 112 <= r && r <= 122: // ['p','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 18
		case r == 33: // ['!','!']
			return 18
		case r == 34: // ['"','"']
			return 19
		case 35 <= r && r <= 91: // ['#','[']
			return 18
		case r == 92: // ['\','\']
			return 20
		case 93 <= r && r <= 1114111: // [']',\U0010ffff]
			return 18
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 29
		case r == 47: // ['/','/']
			return 29
		case r == 92: // ['\','\']
			return 29
		case r == 98: // ['b','b']
			return 29
		case r == 102: // ['f','f']
			return 29
		case r == 110: // ['n','n']
			return 29
		case r == 114: // ['r','r']
			return 29
		case r == 116: // ['t','t']
			return 29
		case r == 117: // ['u','u']
			return 30
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 4
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 4
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 4
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 4
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 67: // ['A','C']
			return 13
		case r == 68: // ['D','D']
			return 31
		case 69 <= r && r <= 90: // ['E','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 104: // ['a','h']
			return 13
		case r == 105: // ['i','i']
			return 32
		case 106 <= r && r <= 122: // ['j','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 115: // ['a','s']
			return 13
		case r == 116: // ['t','t']
			return 33
		case 117 <= r && r <= 122: // ['u','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 18
		case r == 33: // ['!','!']
			return 18
		case r == 34: // ['"','"']
			return 19
		case 35 <= r && r <= 91: // ['#','[']
			return 18
		case r == 92: // ['\','\']
			return 20
		case 93 <= r && r <= 1114111: // [']',\U0010ffff]
			return 18
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 34
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 114: // ['a','r']
			return 13
		case r == 115: // ['s','s']
			return 35
		case 116 <= r && r <= 122: // ['t','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 100: // ['a','d']
			return 13
		case r == 101: // ['e','e']
			return 36
		case 102 <= r && r <= 104: // ['f','h']
			return 13
		case r == 105: // ['i','i']
			return 37
		case 106 <= r && r <= 122: // ['j','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 38
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 115: // ['a','s']
			return 13
		case r == 116: // ['t','t']
			return 39
		case 117 <= r && r <= 122: // ['u','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 119: // ['a','w']
			return 13
		case r == 120: // ['x','x']
			return 40
		case 121 <= r && r <= 122: // ['y','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 109: // ['a','m']
			return 13
		case r == 110: // ['n','n']
			return 41
		case 111 <= r && r <= 122: // ['o','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 42
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 114: // ['a','r']
			return 13
		case r == 115: // ['s','s']
			return 43
		case 116 <= r && r <= 122: // ['t','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 104: // ['a','h']
			return 13
		case r == 105: // ['i','i']
			return 44
		case 106 <= r && r <= 122: // ['j','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 45
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 114: // ['a','r']
			return 13
		case r == 115: // ['s','s']
			return 46
		case 116 <= r && r <= 122: // ['t','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 18
		case r == 33: // ['!','!']
			return 18
		case r == 34: // ['"','"']
			return 19
		case 35 <= r && r <= 91: // ['#','[']
			return 18
		case r == 92: // ['\','\']
			return 20
		case 93 <= r && r <= 1114111: // [']',\U0010ffff]
			return 18
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 115: // ['a','s']
			return 13
		case r == 116: // ['t','t']
			return 47
		case 117 <= r && r <= 122: // ['u','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 114: // ['a','r']
			return 13
		case r == 115: // ['s','s']
			return 48
		case 116 <= r && r <= 122: // ['t','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case r == 35: // ['#','#']
			return 4
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 4
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 45: // ['-','-']
			return 4
		case r == 46: // ['.','.']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case r == 63: // ['?','?']
			return 4
		case 65 <= r && r <= 90: // ['A','Z']
			return 13
		case r == 94: // ['^','^']
			return 4
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 13
		case r == 123: // ['{','{']
			return 4
		case r == 124: // ['|','|']
			return 4
		case r == 125: // ['}','}']
			return 4
		case r == 126: // ['~','~']
			return 4
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 4
		}
		return NoState
	},
}
