// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: pkg/api/v1/service.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ValueType int32

const (
	ValueType_STRING  ValueType = 0
	ValueType_INTEGER ValueType = 1
	ValueType_DOUBLE  ValueType = 2
	ValueType_BOOLEAN ValueType = 3
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "STRING",
		1: "INTEGER",
		2: "DOUBLE",
		3: "BOOLEAN",
	}
	ValueType_value = map[string]int32{
		"STRING":  0,
		"INTEGER": 1,
		"DOUBLE":  2,
		"BOOLEAN": 3,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_service_proto_enumTypes[0].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_service_proto_enumTypes[0]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{0}
}

type ObjectView int32

const (
	ObjectView_BASIC  ObjectView = 0
	ObjectView_NORMAL ObjectView = 1
	ObjectView_RICH   ObjectView = 2
)

// Enum value maps for ObjectView.
var (
	ObjectView_name = map[int32]string{
		0: "BASIC",
		1: "NORMAL",
		2: "RICH",
	}
	ObjectView_value = map[string]int32{
		"BASIC":  0,
		"NORMAL": 1,
		"RICH":   2,
	}
)

func (x ObjectView) Enum() *ObjectView {
	p := new(ObjectView)
	*p = x
	return p
}

func (x ObjectView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectView) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_service_proto_enumTypes[1].Descriptor()
}

func (ObjectView) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_service_proto_enumTypes[1]
}

func (x ObjectView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectView.Descriptor instead.
func (ObjectView) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{1}
}

type WatchEventType int32

const (
	WatchEventType_INIT   WatchEventType = 0
	WatchEventType_CREATE WatchEventType = 1
	WatchEventType_UPDATE WatchEventType = 2
	WatchEventType_DELETE WatchEventType = 3
)

// Enum value maps for WatchEventType.
var (
	WatchEventType_name = map[int32]string{
		0: "INIT",
		1: "CREATE",
		2: "UPDATE",
		3: "DELETE",
	}
	WatchEventType_value = map[string]int32{
		"INIT":   0,
		"CREATE": 1,
		"UPDATE": 2,
		"DELETE": 3,
	}
)

func (x WatchEventType) Enum() *WatchEventType {
	p := new(WatchEventType)
	*p = x
	return p
}

func (x WatchEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_service_proto_enumTypes[2].Descriptor()
}

func (WatchEventType) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_service_proto_enumTypes[2]
}

func (x WatchEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEventType.Descriptor instead.
func (WatchEventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{2}
}

type ObjectType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Statuses    map[string]*ObjectStatus `protobuf:"bytes,3,rep,name=statuses,proto3" json:"statuses,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Metas       map[string]*ObjectMeta   `protobuf:"bytes,4,rep,name=metas,proto3" json:"metas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreateTime  *timestamp.Timestamp     `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	DeleteTime  *timestamp.Timestamp     `protobuf:"bytes,6,opt,name=delete_time,json=deleteTime,proto3" json:"delete_time,omitempty"`
}

func (x *ObjectType) Reset() {
	*x = ObjectType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectType) ProtoMessage() {}

func (x *ObjectType) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectType.ProtoReflect.Descriptor instead.
func (*ObjectType) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ObjectType) GetStatuses() map[string]*ObjectStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ObjectType) GetMetas() map[string]*ObjectMeta {
	if x != nil {
		return x.Metas
	}
	return nil
}

func (x *ObjectType) GetCreateTime() *timestamp.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ObjectType) GetDeleteTime() *timestamp.Timestamp {
	if x != nil {
		return x.DeleteTime
	}
	return nil
}

type ObjectStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	States      map[string]*ObjectState `protobuf:"bytes,3,rep,name=states,proto3" json:"states,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ObjectStatus) Reset() {
	*x = ObjectStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStatus) ProtoMessage() {}

func (x *ObjectStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStatus.ProtoReflect.Descriptor instead.
func (*ObjectStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectStatus) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ObjectStatus) GetStates() map[string]*ObjectState {
	if x != nil {
		return x.States
	}
	return nil
}

type ObjectState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ObjectState) Reset() {
	*x = ObjectState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectState) ProtoMessage() {}

func (x *ObjectState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectState.ProtoReflect.Descriptor instead.
func (*ObjectState) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectState) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ObjectMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ValueType   ValueType `protobuf:"varint,3,opt,name=value_type,json=valueType,proto3,enum=zhihu.cmdb.api.v1.ValueType" json:"value_type,omitempty"`
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ObjectMeta) GetValueType() ValueType {
	if x != nil {
		return x.ValueType
	}
	return ValueType_STRING
}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string                      `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name        string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status      string                      `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	State       string                      `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Version     uint64                      `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreateTime  *timestamp.Timestamp        `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime  *timestamp.Timestamp        `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Metas       map[string]*ObjectMetaValue `protobuf:"bytes,9,rep,name=metas,proto3" json:"metas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *Object) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Object) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Object) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Object) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Object) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Object) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Object) GetCreateTime() *timestamp.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Object) GetUpdateTime() *timestamp.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Object) GetMetas() map[string]*ObjectMetaValue {
	if x != nil {
		return x.Metas
	}
	return nil
}

type ObjectMetaValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValueType ValueType `protobuf:"varint,1,opt,name=value_type,json=valueType,proto3,enum=zhihu.cmdb.api.v1.ValueType" json:"value_type,omitempty"`
	Value     string    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ObjectMetaValue) Reset() {
	*x = ObjectMetaValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectMetaValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMetaValue) ProtoMessage() {}

func (x *ObjectMetaValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMetaValue.ProtoReflect.Descriptor instead.
func (*ObjectMetaValue) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectMetaValue) GetValueType() ValueType {
	if x != nil {
		return x.ValueType
	}
	return ValueType_STRING
}

func (x *ObjectMetaValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ObjectListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string     `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	View        ObjectView `protobuf:"varint,2,opt,name=view,proto3,enum=zhihu.cmdb.api.v1.ObjectView" json:"view,omitempty"`
	Query       string     `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	PageToken   string     `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize    int32      `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ShowDeleted bool       `protobuf:"varint,6,opt,name=show_deleted,json=showDeleted,proto3" json:"show_deleted,omitempty"`
}

func (x *ObjectListRequest) Reset() {
	*x = ObjectListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectListRequest) ProtoMessage() {}

func (x *ObjectListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectListRequest.ProtoReflect.Descriptor instead.
func (*ObjectListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectListRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ObjectListRequest) GetView() ObjectView {
	if x != nil {
		return x.View
	}
	return ObjectView_BASIC
}

func (x *ObjectListRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ObjectListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ObjectListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ObjectListRequest) GetShowDeleted() bool {
	if x != nil {
		return x.ShowDeleted
	}
	return false
}

type ObjectGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string     `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	View ObjectView `protobuf:"varint,3,opt,name=view,proto3,enum=zhihu.cmdb.api.v1.ObjectView" json:"view,omitempty"`
}

func (x *ObjectGetRequest) Reset() {
	*x = ObjectGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectGetRequest) ProtoMessage() {}

func (x *ObjectGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectGetRequest.ProtoReflect.Descriptor instead.
func (*ObjectGetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectGetRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ObjectGetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectGetRequest) GetView() ObjectView {
	if x != nil {
		return x.View
	}
	return ObjectView_BASIC
}

type ObjectDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ObjectDeleteRequest) Reset() {
	*x = ObjectDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectDeleteRequest) ProtoMessage() {}

func (x *ObjectDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectDeleteRequest.ProtoReflect.Descriptor instead.
func (*ObjectDeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *ObjectDeleteRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ObjectDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ObjectListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind          string    `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Objects       []*Object `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	NextPageToken string    `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (x *ObjectListResponse) Reset() {
	*x = ObjectListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectListResponse) ProtoMessage() {}

func (x *ObjectListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectListResponse.ProtoReflect.Descriptor instead.
func (*ObjectListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ObjectListResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ObjectListResponse) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ObjectListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ObjectWatchEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []*Object      `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	Type    WatchEventType `protobuf:"varint,2,opt,name=type,proto3,enum=zhihu.cmdb.api.v1.WatchEventType" json:"type,omitempty"`
}

func (x *ObjectWatchEvent) Reset() {
	*x = ObjectWatchEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectWatchEvent) ProtoMessage() {}

func (x *ObjectWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectWatchEvent.ProtoReflect.Descriptor instead.
func (*ObjectWatchEvent) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *ObjectWatchEvent) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ObjectWatchEvent) GetType() WatchEventType {
	if x != nil {
		return x.Type
	}
	return WatchEventType_INIT
}

type ObjectUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object       *Object               `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	UpdateMask   *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	MatchVersion bool                  `protobuf:"varint,3,opt,name=match_version,json=matchVersion,proto3" json:"match_version,omitempty"`
}

func (x *ObjectUpdateRequest) Reset() {
	*x = ObjectUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectUpdateRequest) ProtoMessage() {}

func (x *ObjectUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectUpdateRequest.ProtoReflect.Descriptor instead.
func (*ObjectUpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *ObjectUpdateRequest) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *ObjectUpdateRequest) GetUpdateMask() *field_mask.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *ObjectUpdateRequest) GetMatchVersion() bool {
	if x != nil {
		return x.MatchVersion
	}
	return false
}

type GetObjectTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetObjectTypeRequest) Reset() {
	*x = GetObjectTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectTypeRequest) ProtoMessage() {}

func (x *GetObjectTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectTypeRequest.ProtoReflect.Descriptor instead.
func (*GetObjectTypeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetObjectTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListObjectTypesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShowDeleted bool `protobuf:"varint,1,opt,name=show_deleted,json=showDeleted,proto3" json:"show_deleted,omitempty"`
	Consistent  bool `protobuf:"varint,2,opt,name=consistent,proto3" json:"consistent,omitempty"`
}

func (x *ListObjectTypesRequest) Reset() {
	*x = ListObjectTypesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListObjectTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectTypesRequest) ProtoMessage() {}

func (x *ListObjectTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectTypesRequest.ProtoReflect.Descriptor instead.
func (*ListObjectTypesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListObjectTypesRequest) GetShowDeleted() bool {
	if x != nil {
		return x.ShowDeleted
	}
	return false
}

func (x *ListObjectTypesRequest) GetConsistent() bool {
	if x != nil {
		return x.Consistent
	}
	return false
}

type ListObjectTypesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Types []*ObjectType `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *ListObjectTypesResponse) Reset() {
	*x = ListObjectTypesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListObjectTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectTypesResponse) ProtoMessage() {}

func (x *ListObjectTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectTypesResponse.ProtoReflect.Descriptor instead.
func (*ListObjectTypesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListObjectTypesResponse) GetTypes() []*ObjectType {
	if x != nil {
		return x.Types
	}
	return nil
}

type ObjectTypeUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       *ObjectType           `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	UpdateMask *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
}

func (x *ObjectTypeUpdateRequest) Reset() {
	*x = ObjectTypeUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectTypeUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectTypeUpdateRequest) ProtoMessage() {}

func (x *ObjectTypeUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectTypeUpdateRequest.ProtoReflect.Descriptor instead.
func (*ObjectTypeUpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *ObjectTypeUpdateRequest) GetType() *ObjectType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ObjectTypeUpdateRequest) GetUpdateMask() *field_mask.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

var File_pkg_api_v1_service_proto protoreflect.FileDescriptor

var file_pkg_api_v1_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x7a, 0x68, 0x69, 0x68,
	0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfc,
	0x03, 0x0a, 0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d,
	0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x05,
	0x6d, 0x65, 0x74, 0x61, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x7a, 0x68,
	0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x12, 0x3b, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x5c, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75,
	0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x1a, 0x57, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x33, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xe4, 0x01,
	0x0a, 0x0c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64,
	0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x59, 0x0a, 0x0b, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x7a, 0x68, 0x69, 0x68,
	0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x43, 0x0a, 0x0b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7f, 0x0a, 0x0a, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a,
	0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1c, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0xae, 0x03, 0x0a, 0x06, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x3a, 0x0a, 0x05, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x1a, 0x5c, 0x0a,
	0x0a, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x38, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x7a,
	0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x64, 0x0a, 0x0f, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3b,
	0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0xcf, 0x01, 0x0a, 0x11, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x76,
	0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x7a, 0x68, 0x69, 0x68,
	0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x56, 0x69, 0x65, 0x77, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x14,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x22, 0x6d, 0x0a, 0x10, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x31, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x69, 0x65, 0x77, 0x52, 0x04, 0x76, 0x69,
	0x65, 0x77, 0x22, 0x3d, 0x0a, 0x13, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x85, 0x01, 0x0a, 0x12, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x33, 0x0a, 0x07,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74,
	0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x7e, 0x0a, 0x10, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a,
	0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x21, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xaa, 0x01, 0x0a, 0x13, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x31, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x06, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d,
	0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73,
	0x6b, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x68, 0x6f, 0x77, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x4e, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x7a, 0x68, 0x69, 0x68,
	0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22,
	0x89, 0x01, 0x0a, 0x17, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x7a, 0x68, 0x69, 0x68,
	0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3b,
	0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x52,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x2a, 0x3d, 0x0a, 0x09, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49,
	0x4e, 0x47, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x54, 0x45, 0x47, 0x45, 0x52, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x42, 0x4f, 0x4f, 0x4c, 0x45, 0x41, 0x4e, 0x10, 0x03, 0x2a, 0x2d, 0x0a, 0x0a, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x56, 0x69, 0x65, 0x77, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x41, 0x53, 0x49,
	0x43, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x52, 0x49, 0x43, 0x48, 0x10, 0x02, 0x2a, 0x3e, 0x0a, 0x0e, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49,
	0x4e, 0x49, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a,
	0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x32, 0xa3, 0x05, 0x0a, 0x07, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x73, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e,
	0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x18, 0x12, 0x16, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x2f, 0x7b, 0x74, 0x79, 0x70, 0x65, 0x7d, 0x12, 0x6c, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x23, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63,
	0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x12, 0x1d, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x7b, 0x74, 0x79, 0x70, 0x65,
	0x7d, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0x72, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x26, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x7a, 0x68, 0x69,
	0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x2a, 0x1d, 0x2f,
	0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x7b,
	0x74, 0x79, 0x70, 0x65, 0x7d, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0x5a, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63,
	0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x1a, 0x19, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x1a, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x14, 0x22, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x67, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x26, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x7a, 0x68, 0x69,
	0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x1a, 0x0f, 0x2f,
	0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x3a, 0x01,
	0x2a, 0x12, 0x7c, 0x0a, 0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x24, 0x2e, 0x7a, 0x68, 0x69,
	0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x26, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x12, 0x1e, 0x2f,
	0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x7b,
	0x74, 0x79, 0x70, 0x65, 0x7d, 0x2f, 0x2a, 0x2f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x30, 0x01, 0x32,
	0xdd, 0x03, 0x0a, 0x0b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12,
	0x67, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x7a, 0x68, 0x69, 0x68,
	0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x1d, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75,
	0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x22,
	0x14, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x74, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x2a, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x1f, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x19, 0x1a, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x7b,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63,
	0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2a, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x72, 0x0a, 0x03, 0x47,
	0x65, 0x74, 0x12, 0x27, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x7a, 0x68,
	0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1d, 0x12, 0x1b, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x42,
	0x26, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x7a, 0x68, 0x69, 0x68, 0x75, 0x2e, 0x63, 0x6d, 0x64,
	0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x5a, 0x0d, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_v1_service_proto_rawDescOnce sync.Once
	file_pkg_api_v1_service_proto_rawDescData = file_pkg_api_v1_service_proto_rawDesc
)

func file_pkg_api_v1_service_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_service_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_v1_service_proto_rawDescData)
	})
	return file_pkg_api_v1_service_proto_rawDescData
}

var file_pkg_api_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_api_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_api_v1_service_proto_goTypes = []interface{}{
	(ValueType)(0),                  // 0: zhihu.cmdb.api.v1.ValueType
	(ObjectView)(0),                 // 1: zhihu.cmdb.api.v1.ObjectView
	(WatchEventType)(0),             // 2: zhihu.cmdb.api.v1.WatchEventType
	(*ObjectType)(nil),              // 3: zhihu.cmdb.api.v1.ObjectType
	(*ObjectStatus)(nil),            // 4: zhihu.cmdb.api.v1.ObjectStatus
	(*ObjectState)(nil),             // 5: zhihu.cmdb.api.v1.ObjectState
	(*ObjectMeta)(nil),              // 6: zhihu.cmdb.api.v1.ObjectMeta
	(*Object)(nil),                  // 7: zhihu.cmdb.api.v1.Object
	(*ObjectMetaValue)(nil),         // 8: zhihu.cmdb.api.v1.ObjectMetaValue
	(*ObjectListRequest)(nil),       // 9: zhihu.cmdb.api.v1.ObjectListRequest
	(*ObjectGetRequest)(nil),        // 10: zhihu.cmdb.api.v1.ObjectGetRequest
	(*ObjectDeleteRequest)(nil),     // 11: zhihu.cmdb.api.v1.ObjectDeleteRequest
	(*ObjectListResponse)(nil),      // 12: zhihu.cmdb.api.v1.ObjectListResponse
	(*ObjectWatchEvent)(nil),        // 13: zhihu.cmdb.api.v1.ObjectWatchEvent
	(*ObjectUpdateRequest)(nil),     // 14: zhihu.cmdb.api.v1.ObjectUpdateRequest
	(*GetObjectTypeRequest)(nil),    // 15: zhihu.cmdb.api.v1.GetObjectTypeRequest
	(*ListObjectTypesRequest)(nil),  // 16: zhihu.cmdb.api.v1.ListObjectTypesRequest
	(*ListObjectTypesResponse)(nil), // 17: zhihu.cmdb.api.v1.ListObjectTypesResponse
	(*ObjectTypeUpdateRequest)(nil), // 18: zhihu.cmdb.api.v1.ObjectTypeUpdateRequest
	nil,                             // 19: zhihu.cmdb.api.v1.ObjectType.StatusesEntry
	nil,                             // 20: zhihu.cmdb.api.v1.ObjectType.MetasEntry
	nil,                             // 21: zhihu.cmdb.api.v1.ObjectStatus.StatesEntry
	nil,                             // 22: zhihu.cmdb.api.v1.Object.MetasEntry
	(*timestamp.Timestamp)(nil),     // 23: google.protobuf.Timestamp
	(*field_mask.FieldMask)(nil),    // 24: google.protobuf.FieldMask
}
var file_pkg_api_v1_service_proto_depIdxs = []int32{
	19, // 0: zhihu.cmdb.api.v1.ObjectType.statuses:type_name -> zhihu.cmdb.api.v1.ObjectType.StatusesEntry
	20, // 1: zhihu.cmdb.api.v1.ObjectType.metas:type_name -> zhihu.cmdb.api.v1.ObjectType.MetasEntry
	23, // 2: zhihu.cmdb.api.v1.ObjectType.create_time:type_name -> google.protobuf.Timestamp
	23, // 3: zhihu.cmdb.api.v1.ObjectType.delete_time:type_name -> google.protobuf.Timestamp
	21, // 4: zhihu.cmdb.api.v1.ObjectStatus.states:type_name -> zhihu.cmdb.api.v1.ObjectStatus.StatesEntry
	0,  // 5: zhihu.cmdb.api.v1.ObjectMeta.value_type:type_name -> zhihu.cmdb.api.v1.ValueType
	23, // 6: zhihu.cmdb.api.v1.Object.create_time:type_name -> google.protobuf.Timestamp
	23, // 7: zhihu.cmdb.api.v1.Object.update_time:type_name -> google.protobuf.Timestamp
	22, // 8: zhihu.cmdb.api.v1.Object.metas:type_name -> zhihu.cmdb.api.v1.Object.MetasEntry
	0,  // 9: zhihu.cmdb.api.v1.ObjectMetaValue.value_type:type_name -> zhihu.cmdb.api.v1.ValueType
	1,  // 10: zhihu.cmdb.api.v1.ObjectListRequest.view:type_name -> zhihu.cmdb.api.v1.ObjectView
	1,  // 11: zhihu.cmdb.api.v1.ObjectGetRequest.view:type_name -> zhihu.cmdb.api.v1.ObjectView
	7,  // 12: zhihu.cmdb.api.v1.ObjectListResponse.objects:type_name -> zhihu.cmdb.api.v1.Object
	7,  // 13: zhihu.cmdb.api.v1.ObjectWatchEvent.objects:type_name -> zhihu.cmdb.api.v1.Object
	2,  // 14: zhihu.cmdb.api.v1.ObjectWatchEvent.type:type_name -> zhihu.cmdb.api.v1.WatchEventType
	7,  // 15: zhihu.cmdb.api.v1.ObjectUpdateRequest.object:type_name -> zhihu.cmdb.api.v1.Object
	24, // 16: zhihu.cmdb.api.v1.ObjectUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	3,  // 17: zhihu.cmdb.api.v1.ListObjectTypesResponse.types:type_name -> zhihu.cmdb.api.v1.ObjectType
	3,  // 18: zhihu.cmdb.api.v1.ObjectTypeUpdateRequest.type:type_name -> zhihu.cmdb.api.v1.ObjectType
	24, // 19: zhihu.cmdb.api.v1.ObjectTypeUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	4,  // 20: zhihu.cmdb.api.v1.ObjectType.StatusesEntry.value:type_name -> zhihu.cmdb.api.v1.ObjectStatus
	6,  // 21: zhihu.cmdb.api.v1.ObjectType.MetasEntry.value:type_name -> zhihu.cmdb.api.v1.ObjectMeta
	5,  // 22: zhihu.cmdb.api.v1.ObjectStatus.StatesEntry.value:type_name -> zhihu.cmdb.api.v1.ObjectState
	8,  // 23: zhihu.cmdb.api.v1.Object.MetasEntry.value:type_name -> zhihu.cmdb.api.v1.ObjectMetaValue
	9,  // 24: zhihu.cmdb.api.v1.Objects.List:input_type -> zhihu.cmdb.api.v1.ObjectListRequest
	10, // 25: zhihu.cmdb.api.v1.Objects.Get:input_type -> zhihu.cmdb.api.v1.ObjectGetRequest
	11, // 26: zhihu.cmdb.api.v1.Objects.Delete:input_type -> zhihu.cmdb.api.v1.ObjectDeleteRequest
	7,  // 27: zhihu.cmdb.api.v1.Objects.Create:input_type -> zhihu.cmdb.api.v1.Object
	14, // 28: zhihu.cmdb.api.v1.Objects.Update:input_type -> zhihu.cmdb.api.v1.ObjectUpdateRequest
	9,  // 29: zhihu.cmdb.api.v1.Objects.Watch:input_type -> zhihu.cmdb.api.v1.ObjectListRequest
	3,  // 30: zhihu.cmdb.api.v1.ObjectTypes.Create:input_type -> zhihu.cmdb.api.v1.ObjectType
	18, // 31: zhihu.cmdb.api.v1.ObjectTypes.Update:input_type -> zhihu.cmdb.api.v1.ObjectTypeUpdateRequest
	16, // 32: zhihu.cmdb.api.v1.ObjectTypes.List:input_type -> zhihu.cmdb.api.v1.ListObjectTypesRequest
	15, // 33: zhihu.cmdb.api.v1.ObjectTypes.Get:input_type -> zhihu.cmdb.api.v1.GetObjectTypeRequest
	12, // 34: zhihu.cmdb.api.v1.Objects.List:output_type -> zhihu.cmdb.api.v1.ObjectListResponse
	7,  // 35: zhihu.cmdb.api.v1.Objects.Get:output_type -> zhihu.cmdb.api.v1.Object
	7,  // 36: zhihu.cmdb.api.v1.Objects.Delete:output_type -> zhihu.cmdb.api.v1.Object
	7,  // 37: zhihu.cmdb.api.v1.Objects.Create:output_type -> zhihu.cmdb.api.v1.Object
	7,  // 38: zhihu.cmdb.api.v1.Objects.Update:output_type -> zhihu.cmdb.api.v1.Object
	13, // 39: zhihu.cmdb.api.v1.Objects.Watch:output_type -> zhihu.cmdb.api.v1.ObjectWatchEvent
	3,  // 40: zhihu.cmdb.api.v1.ObjectTypes.Create:output_type -> zhihu.cmdb.api.v1.ObjectType
	3,  // 41: zhihu.cmdb.api.v1.ObjectTypes.Update:output_type -> zhihu.cmdb.api.v1.ObjectType
	17, // 42: zhihu.cmdb.api.v1.ObjectTypes.List:output_type -> zhihu.cmdb.api.v1.ListObjectTypesResponse
	3,  // 43: zhihu.cmdb.api.v1.ObjectTypes.Get:output_type -> zhihu.cmdb.api.v1.ObjectType
	34, // [34:44] is the sub-list for method output_type
	24, // [24:34] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_service_proto_init() }
func file_pkg_api_v1_service_proto_init() {
	if File_pkg_api_v1_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectMetaValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectWatchEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjectTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListObjectTypesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListObjectTypesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectTypeUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_v1_service_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_api_v1_service_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_service_proto_depIdxs,
		EnumInfos:         file_pkg_api_v1_service_proto_enumTypes,
		MessageInfos:      file_pkg_api_v1_service_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_service_proto = out.File
	file_pkg_api_v1_service_proto_rawDesc = nil
	file_pkg_api_v1_service_proto_goTypes = nil
	file_pkg_api_v1_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ObjectsClient is the client API for Objects service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObjectsClient interface {
	List(ctx context.Context, in *ObjectListRequest, opts ...grpc.CallOption) (*ObjectListResponse, error)
	Get(ctx context.Context, in *ObjectGetRequest, opts ...grpc.CallOption) (*Object, error)
	Delete(ctx context.Context, in *ObjectDeleteRequest, opts ...grpc.CallOption) (*Object, error)
	Create(ctx context.Context, in *Object, opts ...grpc.CallOption) (*Object, error)
	Update(ctx context.Context, in *ObjectUpdateRequest, opts ...grpc.CallOption) (*Object, error)
	Watch(ctx context.Context, in *ObjectListRequest, opts ...grpc.CallOption) (Objects_WatchClient, error)
}

type objectsClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectsClient(cc grpc.ClientConnInterface) ObjectsClient {
	return &objectsClient{cc}
}

func (c *objectsClient) List(ctx context.Context, in *ObjectListRequest, opts ...grpc.CallOption) (*ObjectListResponse, error) {
	out := new(ObjectListResponse)
	err := c.cc.Invoke(ctx, "/zhihu.cmdb.api.v1.Objects/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectsClient) Get(ctx context.Context, in *ObjectGetRequest, opts ...grpc.CallOption) (*Object, error) {
	out := new(Object)
	err := c.cc.Invoke(ctx, "/zhihu.cmdb.api.v1.Objects/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectsClient) Delete(ctx context.Context, in *ObjectDeleteRequest, opts ...grpc.CallOption) (*Object, error) {
	out := new(Object)
	err := c.cc.Invoke(ctx, "/zhihu.cmdb.api.v1.Objects/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectsClient) Create(ctx context.Context, in *Object, opts ...grpc.CallOption) (*Object, error) {
	out := new(Object)
	err := c.cc.Invoke(ctx, "/zhihu.cmdb.api.v1.Objects/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectsClient) Update(ctx context.Context, in *ObjectUpdateRequest, opts ...grpc.CallOption) (*Object, error) {
	out := new(Object)
	err := c.cc.Invoke(ctx, "/zhihu.cmdb.api.v1.Objects/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectsClient) Watch(ctx context.Context, in *ObjectListRequest, opts ...grpc.CallOption) (Objects_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Objects_serviceDesc.Streams[0], "/zhihu.cmdb.api.v1.Objects/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &objectsWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Objects_WatchClient interface {
	Recv() (*ObjectWatchEvent, error)
	grpc.ClientStream
}

type objectsWatchClient struct {
	grpc.ClientStream
}

func (x *objectsWatchClient) Recv() (*ObjectWatchEvent, error) {
	m := new(ObjectWatchEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ObjectsServer is the server API for Objects service.
type ObjectsServer interface {
	List(context.Context, *ObjectListRequest) (*ObjectListResponse, error)
	Get(context.Context, *ObjectGetRequest) (*Object, error)
	Delete(context.Context, *ObjectDeleteRequest) (*Object, error)
	Create(context.Context, *Object) (*Object, error)
	Update(context.Context, *ObjectUpdateRequest) (*Object, error)
	Watch(*ObjectListRequest, Objects_WatchServer) error
}

// UnimplementedObjectsServer can be embedded to have forward compatible implementations.
type UnimplementedObjectsServer struct {
}

func (*UnimplementedObjectsServer) List(context.Context, *ObjectListRequest) (*ObjectListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedObjectsServer) Get(context.Context, *ObjectGetRequest) (*Object, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedObjectsServer) Delete(context.Context, *ObjectDeleteRequest) (*Object, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedObjectsServer) Create(context.Context, *Object) (*Object, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedObjectsServer) Update(context.Context, *ObjectUpdateRequest) (*Object, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedObjectsServer) Watch(*ObjectListRequest, Objects_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}

func RegisterObjectsServer(s *grpc.Server, srv ObjectsServer) {
	s.RegisterService(&_Objects_serviceDesc, srv)
}

func _Objects_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zhihu.cmdb.api.v1.Objects/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectsServer).List(ctx, req.(*ObjectListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Objects_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zhihu.cmdb.api.v1.Objects/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectsServer).Get(ctx, req.(*ObjectGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Objects_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zhihu.cmdb.api.v1.Objects/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectsServer).Delete(ctx, req.(*ObjectDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Objects_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Object)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zhihu.cmdb.api.v1.Objects/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectsServer).Create(ctx, req.(*Object))
	}
	return interceptor(ctx, in, info, handler)
}

func _Objects_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zhihu.cmdb.api.v1.Objects/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectsServer).Update(ctx, req.(*ObjectUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Objects_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObjectListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObjectsServer).Watch(m, &objectsWatchServer{stream})
}

type Objects_WatchServer interface {
	Send(*ObjectWatchEvent) error
	grpc.ServerStream
}

type objectsWatchServer struct {
	grpc.ServerStream
}

func (x *objectsWatchServer) Send(m *ObjectWatchEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _Objects_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zhihu.cmdb.api.v1.Objects",
	HandlerType: (*ObjectsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Objects_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Objects_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Objects_Delete_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Objects_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Objects_Update_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Objects_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/api/v1/service.proto",
}

// ObjectTypesClient is the client API for ObjectTypes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObjectTypesClient interface {
	Create(ctx context.Context, in *ObjectType, opts ...grpc.CallOption) (*ObjectType, error)
	Update(ctx context.Context, in *ObjectTypeUpdateRequest, opts ...grpc.CallOption) (*ObjectType, error)
	List(ctx context.Context, in *ListObjectTypesRequest, opts ...grpc.CallOption) (*ListObjectTypesResponse, error)
	Get(ctx context.Context, in *GetObjectTypeRequest, opts ...grpc.CallOption) (*ObjectType, error)
}

type objectTypesClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectTypesClient(cc grpc.ClientConnInterface) ObjectTypesClient {
	return &objectTypesClient{cc}
}

func (c *objectTypesClient) Create(ctx context.Context, in *ObjectType, opts ...grpc.CallOption) (*ObjectType, error) {
	out := new(ObjectType)
	err := c.cc.Invoke(ctx, "/zhihu.cmdb.api.v1.ObjectTypes/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectTypesClient) Update(ctx context.Context, in *ObjectTypeUpdateRequest, opts ...grpc.CallOption) (*ObjectType, error) {
	out := new(ObjectType)
	err := c.cc.Invoke(ctx, "/zhihu.cmdb.api.v1.ObjectTypes/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectTypesClient) List(ctx context.Context, in *ListObjectTypesRequest, opts ...grpc.CallOption) (*ListObjectTypesResponse, error) {
	out := new(ListObjectTypesResponse)
	err := c.cc.Invoke(ctx, "/zhihu.cmdb.api.v1.ObjectTypes/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectTypesClient) Get(ctx context.Context, in *GetObjectTypeRequest, opts ...grpc.CallOption) (*ObjectType, error) {
	out := new(ObjectType)
	err := c.cc.Invoke(ctx, "/zhihu.cmdb.api.v1.ObjectTypes/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectTypesServer is the server API for ObjectTypes service.
type ObjectTypesServer interface {
	Create(context.Context, *ObjectType) (*ObjectType, error)
	Update(context.Context, *ObjectTypeUpdateRequest) (*ObjectType, error)
	List(context.Context, *ListObjectTypesRequest) (*ListObjectTypesResponse, error)
	Get(context.Context, *GetObjectTypeRequest) (*ObjectType, error)
}

// UnimplementedObjectTypesServer can be embedded to have forward compatible implementations.
type UnimplementedObjectTypesServer struct {
}

func (*UnimplementedObjectTypesServer) Create(context.Context, *ObjectType) (*ObjectType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedObjectTypesServer) Update(context.Context, *ObjectTypeUpdateRequest) (*ObjectType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedObjectTypesServer) List(context.Context, *ListObjectTypesRequest) (*ListObjectTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedObjectTypesServer) Get(context.Context, *GetObjectTypeRequest) (*ObjectType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterObjectTypesServer(s *grpc.Server, srv ObjectTypesServer) {
	s.RegisterService(&_ObjectTypes_serviceDesc, srv)
}

func _ObjectTypes_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectTypesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zhihu.cmdb.api.v1.ObjectTypes/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectTypesServer).Create(ctx, req.(*ObjectType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectTypes_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectTypeUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectTypesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zhihu.cmdb.api.v1.ObjectTypes/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectTypesServer).Update(ctx, req.(*ObjectTypeUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectTypes_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectTypesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zhihu.cmdb.api.v1.ObjectTypes/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectTypesServer).List(ctx, req.(*ListObjectTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectTypes_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectTypesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zhihu.cmdb.api.v1.ObjectTypes/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectTypesServer).Get(ctx, req.(*GetObjectTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ObjectTypes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zhihu.cmdb.api.v1.ObjectTypes",
	HandlerType: (*ObjectTypesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ObjectTypes_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ObjectTypes_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ObjectTypes_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ObjectTypes_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/v1/service.proto",
}
