// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 11

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Expression
		2,  // Condition
		-1, // Values
		-1, // Value
		3,  // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		6,  // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		9,  // InOperator
		12, // ExistOperator
		-1, // And
		10, // Operator
		11, // EqualOperator
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		21, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Expression
		23, // Condition
		-1, // Values
		-1, // Value
		3,  // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		25, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		28, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Expression
		-1, // Condition
		29, // Values
		30, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		35, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Expression
		-1, // Condition
		-1, // Values
		-1, // Value
		-1, // MetaName
		-1, // InOperator
		-1, // ExistOperator
		-1, // And
		-1, // Operator
		-1, // EqualOperator
	},
}
