// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/zhihu/cmdb/pkg/server"
	"github.com/zhihu/cmdb/pkg/storage/tidb"
)

// Injectors from wire.go:

func InitServer(ctx context.Context, dsn tidb.DSN) (*server.Server, error) {
	storage, err := tidb.NewStorage(dsn)
	if err != nil {
		return nil, err
	}
	objects := &server.Objects{
		Storage: storage,
	}
	serverServer := &server.Server{
		Objects: objects,
	}
	return serverServer, nil
}
